# Generated by Django 4.2 on 2023-12-31 06:56

import django.db.models.deletion
from django.db import migrations, models

import goods.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Название категории",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг категории")),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Порядковый номер"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорию",
                "verbose_name_plural": "Категории",
                "db_table": "category",
                "ordering": ("z_index",),
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Слаг продукта"
                    ),
                ),
                (
                    "z_index",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Порядковый номер"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=goods.models.product_image_upload_to,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        null=True,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        null=True,
                        verbose_name="Скидка %",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="Количество"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="goods.categories",
                        verbose_name="Категория продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "db_table": "product",
                "ordering": ("z_index",),
            },
        ),
    ]
