# Generated by Django 4.2 on 2023-12-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0004_alter_products_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="slug",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Слаг продукта"
            ),
        ),
    ]
